package caverace

WINDOW_WIDTH  :: 640
WINDOW_HEIGHT :: 400
WINDOW_TITLE  :: "CaveRace"
TARGET_FPS    :: 60

MAP_WIDTH     :: 19
MAP_HEIGHT    :: 11
MAP_TILE_SIZE :: 32
MAP_OFFSET_X  :: 16
MAP_OFFSET_Y  :: 8

#assert(MAP_OFFSET_X * 2 + MAP_WIDTH * MAP_TILE_SIZE == WINDOW_WIDTH)
#assert(MAP_OFFSET_Y + MAP_HEIGHT * MAP_TILE_SIZE <= WINDOW_HEIGHT)

MEDIA_PATH    :: "media"
